"""Lexicon terms for closed-set genre scoring. Lowercase phrases."""

from __future__ import annotations

from exlibris.genres import EROTICA_LABEL

# Distinctive topical terms. Overlap is OK; scoring prefers density.
GENRE_LEXICONS: dict[str, tuple[str, ...]] = {
    "Literary Fiction": (
        "literary",
        "prose",
        "narrator",
        "interiority",
        "novella",
        "the novel",
        "character study",
    ),
    "Contemporary Fiction": (
        "apartment",
        "suburb",
        "office",
        "smartphone",
        "email",
        "divorce",
        "contemporary",
        "today",
    ),
    "Historical Fiction": (
        "historical fiction",
        "regency",
        "victorian",
        "medieval",
        "the year 18",
        "horse-drawn",
        "carriage",
        "king's court",
        "period dress",
    ),
    "Fantasy": (
        "dragon",
        "wizard",
        "witch",
        "magic",
        "spell",
        "elf",
        "elves",
        "dwarf",
        "sorcerer",
        "quest",
        "enchanted",
        "kingdom",
        "sword",
        "prophecy",
        "mage",
    ),
    "Science Fiction": (
        "spaceship",
        "starship",
        "android",
        "robot",
        "hyperspace",
        "galaxy",
        "alien",
        "warp",
        "terraforming",
        "cybernetic",
        "space station",
        "laser",
        "colonists",
    ),
    "Mystery": (
        "detective",
        "whodunit",
        "clue",
        "suspect",
        "alibi",
        "sleuth",
        "investigation",
        "murder mystery",
        "inspector",
    ),
    "Thriller": (
        "thriller",
        "ticking",
        "conspiracy",
        "assassin",
        "on the run",
        "hostage",
        "deadline",
        "chase",
        "adrenaline",
    ),
    "Crime": (
        "gangster",
        "heist",
        "mafia",
        "mob",
        "underworld",
        "cartel",
        "crime scene",
        "felony",
    ),
    "Horror": (
        "horror",
        "haunted",
        "nightmare",
        "scream",
        "blood-soaked",
        "ghoul",
        "demon",
        "terror",
        "macabre",
        "undead",
    ),
    "Romance": (
        "romance",
        "kissed",
        "kiss",
        "beloved",
        "darling",
        "heart raced",
        "falling in love",
        "wedding",
        "courting",
        "soulmate",
    ),
    EROTICA_LABEL: (
        "erotica",
        "erotic",
        "explicit sex",
        "lovemaking",
        "arousal",
    ),
    "Adventure": (
        "adventure",
        "expedition",
        "jungle",
        "treasure",
        "map",
        "explorer",
        "peril",
        "voyage",
    ),
    "Western": (
        "sheriff",
        "cowboy",
        "saloon",
        "outlaw",
        "frontier",
        "ranch",
        "stagecoach",
        "gunslinger",
        "the west",
    ),
    "War Fiction": (
        "trench",
        "battlefield",
        "platoon",
        "artillery",
        "infantry",
        "front line",
        "soldier",
        "enlisted",
        "combat",
    ),
    "Humor": (
        "hilarious",
        "comic",
        "satire",
        "joked",
        "punchline",
        "absurd",
        "witty",
        "farce",
    ),
    "Paranormal": (
        "vampire",
        "werewolf",
        "ghost",
        "psychic",
        "supernatural",
        "shapeshifter",
        "medium",
        "haunting",
    ),
    "Dystopian": (
        "dystopia",
        "dystopian",
        "totalitarian",
        "regime",
        "surveillance state",
        "oppressed",
        "the capitol",
        "rebellion",
    ),
    "Magical Realism": (
        "magical realism",
        "everyday magic",
        "impossible yet",
        "realism",
    ),
    "Young Adult": (
        "high school",
        "sophomore",
        "prom",
        "teenager",
        "coming of age",
        "ninth grade",
        "dorm",
    ),
    "Middle Grade": (
        "middle school",
        "sixth grade",
        "recess",
        "best friend",
        "eleven-year-old",
        "twelve-year-old",
    ),
    "Children's": (
        "picture book",
        "once upon a time",
        "bedtime",
        "mommy",
        "daddy",
        "little bear",
        "for children",
    ),
    "Short Stories": (
        "short story",
        "short stories",
        "collection of stories",
        "the stories in this",
    ),
    "Poetry": (
        "poem",
        "stanza",
        "verse",
        "sonnet",
        "poet",
        "rhyme",
        "lyric",
    ),
    "Drama": (
        "act one",
        "stage direction",
        "playwright",
        "curtain",
        "dramatic",
        "scene i",
        "enter ",
    ),
    "Biography": (
        "biography",
        "biographical",
        "was born",
        "early life",
        "died in",
        "his career",
        "her career",
        "life of",
    ),
    "Memoir": (
        "memoir",
        "i remember",
        "my childhood",
        "looking back",
        "autobiograph",
        "years later i",
    ),
    "History": (
        "historian",
        "historical record",
        "century",
        "primary source",
        "in the year",
        "empire",
        "archive",
        "chronology",
    ),
    "Military History": (
        "military history",
        "campaign",
        "battalion",
        "strategy",
        "naval",
        "generals",
        "war history",
    ),
    "Politics": (
        "election",
        "legislature",
        "policy",
        "senator",
        "parliament",
        "democrat",
        "republican",
        "political",
        "government",
    ),
    "Philosophy": (
        "philosophy",
        "philosopher",
        "epistemology",
        "metaphysics",
        "ethics",
        "kant",
        "aristotle",
        "argument that",
    ),
    "Religion": (
        "theology",
        "scripture",
        "church",
        "bible",
        "quran",
        "gospel",
        "congregation",
        "faith",
        "worship",
    ),
    "Spirituality": (
        "spirituality",
        "meditation",
        "mindfulness",
        "inner peace",
        "chakras",
        "enlightenment",
        "soul",
    ),
    "Psychology": (
        "psychology",
        "cognitive",
        "behavior",
        "therapist",
        "unconscious",
        "clinical",
        "personality",
        "mental health",
    ),
    "Self-Help": (
        "self-help",
        "you can",
        "habits",
        "takeaway",
        "workbook",
        "in this book you",
        "steps to",
        "improve your",
    ),
    "Business": (
        "management",
        "startup",
        "ceo",
        "corporate",
        "market share",
        "leadership",
        "entrepreneur",
        "business",
    ),
    "Economics": (
        "economics",
        "economist",
        "gdp",
        "inflation",
        "supply and demand",
        "macroeconomic",
        "fiscal",
    ),
    "Personal Finance": (
        "retirement",
        "budget",
        "investing",
        "mortgage",
        "credit score",
        "savings",
        "personal finance",
    ),
    "Science": (
        "hypothesis",
        "experiment",
        "scientific",
        "laboratory",
        "peer-reviewed",
        "physics",
        "chemistry",
        "biology",
        "researcher",
    ),
    "Mathematics": (
        "theorem",
        "equation",
        "algebra",
        "calculus",
        "proof",
        "integer",
        "mathematics",
        "lemma",
    ),
    "Technology": (
        "innovation",
        "gadget",
        "engineering",
        "patent",
        "silicon",
        "device",
        "technology",
    ),
    "Computers": (
        "software",
        "programming",
        "algorithm",
        "compiler",
        "python",
        "database",
        "operating system",
        "source code",
    ),
    "Medicine": (
        "diagnosis",
        "patient",
        "clinical trial",
        "anatomy",
        "physician",
        "surgery",
        "pathology",
        "medical",
    ),
    "Health and Fitness": (
        "workout",
        "nutrition",
        "calories",
        "exercise",
        "fitness",
        "diet",
        "weight loss",
        "gym",
    ),
    "Nature": (
        "wildlife",
        "forest",
        "species",
        "habitat",
        "bird",
        "wilderness",
        "naturalist",
        "flora",
    ),
    "Environment": (
        "climate change",
        "carbon",
        "pollution",
        "ecosystem",
        "conservation",
        "sustainability",
        "greenhouse",
    ),
    "Travel": (
        "guidebook",
        "itinerary",
        "tourist",
        "destination",
        "travel",
        "passport",
        "hotel",
        "journey to",
    ),
    "True Crime": (
        "true crime",
        "serial killer",
        "prosecutor",
        "trial",
        "forensic",
        "convicted",
        "the victim",
        "police report",
    ),
    "Education": (
        "curriculum",
        "classroom",
        "pedagogy",
        "students",
        "teacher",
        "lesson",
        "school district",
    ),
    "Reference": (
        "encyclopedia",
        "dictionary",
        "handbook",
        "appendix",
        "see also",
        "glossary",
        "reference",
    ),
    "Language": (
        "grammar",
        "vocabulary",
        "linguistics",
        "pronunciation",
        "syntax",
        "translation",
        "language learning",
    ),
    "Art": (
        "painting",
        "sculpture",
        "gallery",
        "artist",
        "canvas",
        "museum",
        "impressionist",
        "art history",
    ),
    "Music": (
        "symphony",
        "composer",
        "melody",
        "orchestra",
        "album",
        "musician",
        "chord",
        "concerto",
    ),
    "Cooking": (
        "recipe",
        "ingredient",
        "preheat",
        "tablespoon",
        "cookbook",
        "simmer",
        "oven",
        "cuisine",
    ),
    "Crafts and Hobbies": (
        "knitting",
        "sewing",
        "woodworking",
        "hobby",
        "diy",
        "craft",
        "pattern",
        "stitch",
    ),
    "Sports": (
        "championship",
        "coach",
        "athlete",
        "tournament",
        "league",
        "football",
        "baseball",
        "soccer",
        "basketball",
    ),
    "Parenting": (
        "toddler",
        "parenting",
        "newborn",
        "childcare",
        "your child",
        "pregnancy",
        "baby",
    ),
    "Law": (
        "statute",
        "court",
        "plaintiff",
        "jurisdiction",
        "legal",
        "attorney",
        "constitutional",
        "case law",
    ),
    "Social Science": (
        "sociology",
        "anthropology",
        "qualitative",
        "survey",
        "demographics",
        "social science",
        "ethnography",
    ),
    "Essays": (
        "essay",
        "essays",
        "in this essay",
        "collection of essays",
        "the essayist",
    ),
    "Journalism": (
        "reporter",
        "newspaper",
        "headline",
        "correspondent",
        "investigative",
        "journalism",
        "the press",
    ),
}

# Explicit sexual terms for the adult overlay (not mild romance).
EXPLICIT_TERMS: tuple[str, ...] = (
    "cock",
    "cocks",
    "pussy",
    "cunt",
    "fuck",
    "fucked",
    "fucking",
    "orgasm",
    "orgasms",
    "clitoris",
    "penis",
    "vagina",
    "ejaculat",
    "blowjob",
    "handjob",
    "cumming",
    "cummed",
    "moaned as he",
    "moaned as she",
    "spread her legs",
    "thrust into",
    "hard cock",
    "wet pussy",
)

FICTION_STYLE_TERMS: tuple[str, ...] = (
    "said",
    "asked",
    "replied",
    "whispered",
    "chapter",
    "he said",
    "she said",
)

NONFICTION_STYLE_TERMS: tuple[str, ...] = (
    "according to",
    "this book",
    "in this book",
    "figure 1",
    "table 1",
    "for example",
    "the author",
    "et al",
    "introduction",
    "references",
    "isbn",
)
